services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeigniter_app
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/codeigniter/public
      - .:/var/www/codeigniter
    working_dir: /var/www/codeigniter
    environment:
      CI_ENVIRONMENT: development
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: codeigniter_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: codeigniter_db
      MYSQL_USER: codeigniter_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
