name: CI/CD for Develop

on:
  push:
    branches:
      - develop

env:
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
  AZURE_APP_NAME_DEV: ${{ vars.AZURE_APP_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Azure Container Registry Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACRLOGINSERVER }}
          username: ${{ secrets.ACRUSERNAME }}
          password: ${{ secrets.ACRPASSWORD }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.ACRLOGINSERVER }}/${{ env.IMAGE_NAME }}:develop
      
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_NAME_DEV }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
          images: ${{ secrets.ACRLOGINSERVER }}/${{ env.IMAGE_NAME }}:develop