name: CI/CD for Develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    environment: develop
    runs-on: ubuntu-latest
    env:
      REGISTRY_SERVER: ${{ secrets.ACRLOGINSERVER }}.azurecr.io
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      APP_NAME: ${{ vars.AZURE_APP_NAME }}
      AZURE_WEB_APP_PUBLISH_PROFILE: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_SERVER }}
          username: ${{ secrets.ACRUSERNAME }}
          password: ${{ secrets.ACRPASSWORD }}
          
      - name: Set environment variables
        run: |
          echo "database.default.hostname=coxpatentsdevmysql.mysql.database.azure.com" >> .env
          echo "database.default.database=cox_patents_db_dev" >> .env
          echo "database.default.username=coxpatentsdevmysql" >> .env
          echo "database.default.password=a1b1c1d1.." >> .env
          echo "database.default.DBDriver=MySQLi" >> .env
          echo "database.default.port=3306" >> .env    
          echo "app.baseURL=''" >> .env

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}


      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          images: ${{ env.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          publish-profile: ${{ env.AZURE_WEB_APP_PUBLISH_PROFILE }}
